# Generated by Django 4.0.6 on 2022-07-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_degree_alter_profiletype_typename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('Mukyu', 'White belt '), ('10th Kyu', '10 Kyu - Orange belt'), ('9th Kyu', '9th Kyu – Orange belt with blue stripe'), ('8th Kyu', '8th Kyu - Blue belt'), ('7th Kyu', '7th Kyu – Blue belt with green stripe'), ('6th Kyu', '6th Kyu – Yellow belt'), ('5th Kyu', '5th Kyu – Yellow belt with orange stripe'), ('4th Kyu', '4th Kyu – Green belt'), ('3rd Kyu', '3rd Kyu – Green belt with brown stripe'), ('2nd Kyu', '2nd Kyu – Brown belt'), ('1st Kyu', '1st Kyu – Brown belt with black stripe'), ('1st Dan (Shodan)', '1st Dan - The black belt has one gold stripe'), ('1st Dan (Nidan)', '2nd Dan – The black belt has two gold stripes'), ('1st Dan (Sandan)', '3rd Dan – The black belt has three gold stripes'), ('1st Dan (Yondan)', '4th Dan – The black belt has four gold stripes'), ('1st Dan (Godan)', '5th Dan - The black belt has five gold stripes'), ('1st Dan (Rokudan)', '6th Dan – The black belt has six gold stripes'), ('1st Dan (Shichidan)', '7th Dan – The black belt has seven gold stripes'), ('1st Dan (Hachidan)', '8th Dan – The black belt has eight gold stripes'), ('1st Dan (Kyūdan)', '9th Dan – The black belt has nine gold stripes'), ('1st Dan (Jūdan)', '10th Dan – The black belt has ten gold stripes')], max_length=20, null=True),
        ),
    ]
