# Generated by Django 4.0.6 on 2022-08-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileType',
        ),
        migrations.AddField(
            model_name='profile',
            name='profileType',
            field=models.ManyToManyField(blank=True, null=True, to='account.profiletype'),
        ),
    ]
