# Generated by Django 4.0.6 on 2022-08-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(default='Ukraine', max_length=25)),
                ('city', models.CharField(default='Kharkiv', max_length=25)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subscribe_date', models.DateField()),
                ('notes', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='media/events/img/%Y/%m/%d')),
                ('attachment', models.FileField(blank=True, upload_to='media/events/att/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
